# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x0fsn.bambey.users\"\x1c\n\x0eUserGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x0cUserGetReply\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.sn.bambey.users.User\"V\n\x11UserCreateRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"6\n\x0fUserCreateReply\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.sn.bambey.users.User\"b\n\x11UserUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\r\n\x05\x65mail\x18\x05 \x01(\t\"6\n\x0fUserUpdateReply\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.sn.bambey.users.User\"\x1f\n\x11UserDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0fUserDeleteReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10ListUsersRequest\"6\n\x0eListUsersReply\x12$\n\x05users\x18\x01 \x03(\x0b\x32\x15.sn.bambey.users.User\"U\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\r\n\x05\x65mail\x18\x05 \x01(\t2\x9f\x03\n\x05Users\x12I\n\x07GetUser\x12\x1f.sn.bambey.users.UserGetRequest\x1a\x1d.sn.bambey.users.UserGetReply\x12R\n\nCreateUser\x12\".sn.bambey.users.UserCreateRequest\x1a .sn.bambey.users.UserCreateReply\x12R\n\nUpdateUser\x12\".sn.bambey.users.UserUpdateRequest\x1a .sn.bambey.users.UserUpdateReply\x12R\n\nDeleteUser\x12\".sn.bambey.users.UserDeleteRequest\x1a .sn.bambey.users.UserDeleteReply\x12O\n\tListUsers\x12!.sn.bambey.users.ListUsersRequest\x1a\x1f.sn.bambey.users.ListUsersReplyB\x13\n\x0fsn.bambey.usersP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017sn.bambey.usersP\001'
  _globals['_USERGETREQUEST']._serialized_start=32
  _globals['_USERGETREQUEST']._serialized_end=60
  _globals['_USERGETREPLY']._serialized_start=62
  _globals['_USERGETREPLY']._serialized_end=113
  _globals['_USERCREATEREQUEST']._serialized_start=115
  _globals['_USERCREATEREQUEST']._serialized_end=201
  _globals['_USERCREATEREPLY']._serialized_start=203
  _globals['_USERCREATEREPLY']._serialized_end=257
  _globals['_USERUPDATEREQUEST']._serialized_start=259
  _globals['_USERUPDATEREQUEST']._serialized_end=357
  _globals['_USERUPDATEREPLY']._serialized_start=359
  _globals['_USERUPDATEREPLY']._serialized_end=413
  _globals['_USERDELETEREQUEST']._serialized_start=415
  _globals['_USERDELETEREQUEST']._serialized_end=446
  _globals['_USERDELETEREPLY']._serialized_start=448
  _globals['_USERDELETEREPLY']._serialized_end=482
  _globals['_LISTUSERSREQUEST']._serialized_start=484
  _globals['_LISTUSERSREQUEST']._serialized_end=502
  _globals['_LISTUSERSREPLY']._serialized_start=504
  _globals['_LISTUSERSREPLY']._serialized_end=558
  _globals['_USER']._serialized_start=560
  _globals['_USER']._serialized_end=645
  _globals['_USERS']._serialized_start=648
  _globals['_USERS']._serialized_end=1063
# @@protoc_insertion_point(module_scope)
